### PR TITLE
Support Electron 11

### LINKED ISSUE #73: Support Electron 11 (Apple Silicon)
We started to upgrade our Electron version to 11 which is supposed to be tomorrow (according to https://www.electronjs.org/docs/tutorial/electron-timelines). The main reason is that we need to support Apple Silicon hardware (https://www.electronjs.org/blog/apple-silicon). Our app is currently on Electron 10.1.5 (latest stable) with `testcafé@1.9.4` and `testcafe-browser-provider-electron@0.0.15` which works very well.

So I played a bit with `electron@11.0.0-beta.1` and it seemed that we didn't support breaking changes from Electron 11 yet.

Here the error:

Screen Shot 2020-11-16 at 1 45 21 PM

As far as I saw, `process.electronBinding('web_contents')` should be `process._linkedBinding('electron_browser_web_contents');` now according to https://github.com/electron/electron/commit/659e79fc08c6ffc2f7506dd1358918d97d240147. So it leads to `process.electronBinding is not a function` error when starting Electron through the provider.

Please let me know if you need any further information

### PR DESCRIPTION
**Pull request by Farfurix**
Closes #73. 

### Changes
1. Updated the Electron version to `^11.0.3`.
2. Changed `loadURL` patching logic due to [these changes](https://github.com/electron/electron/pull/24325/files#diff-f6ca6a11b1d9a20b2f71e91a51c06f4956adb0eec9f07ac0705190f77c257211R437).
3. [Fixed binding naming](https://github.com/electron/electron/blob/v11.0.3/lib/browser/api/web-contents.ts#L123).
4. Switched on the `enableRemoteModule` ([Electron 10 breaking changes](https://www.electronjs.org/blog/electron-10-0#breaking-changes)).
5. Replaced `var` with `const` and `let` in src/injectable/electron-mocks.js.
6. The Travis CI config: changed the Ubuntu version from 14 (`trusty`) to 20 (`focal`), moved `xvfb` to services.

### CODE REVIEW

**Review by miherlosev — APPROVED** [review]

**Review by AndreyBelym — APPROVED** [review]

**Comment by MrGreenTea** [comment]
When can we expect a release with this support? We would be very grateful for a release soon if possible, so we can start testing our electron 11 support :)

**Comment by Farfurix** [comment]
@MrGreenTea 

Hello,

Now we are working on our `testcafe@1.10.0` release. After that, we will release the provider version.

**Comment by MrGreenTea** [comment]
> @MrGreenTea
> 
> Hello,
> 
> Now we are working on our `testcafe@1.10.0` release. After that, we will release the provider version.

Thanks for the info, looking forward to both ;)

**Comment by zerocewl** [comment]
@Farfurix So `testcafe@1.10.0` was released yesterday. Now you are able to release a new provider version?

**Comment by Farfurix** [comment]
@MrGreenTea @zerocewl 

Hello,

You can track our progress here: https://github.com/DevExpress/testcafe-browser-provider-electron/pull/77.
